spring:
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 数据源相关配置
    shard1:
      druid:
        url: jdbc:mysql://localhost:3306/usercenter_shard1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: tiger
        driverClass: com.mysql.jdbc.Driver
        validationQuery: select 1
        initial-size: 3
        min-idle: 3
        max-active: 10
        max-wait: 60000
    shard2:
      druid:
        url: jdbc:mysql://localhost:3306/usercenter_shard2?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: tiger
        driverClass: com.mysql.jdbc.Driver
        validationQuery: select 1
        initial-size: 3
        min-idle: 3
        max-active: 10
        max-wait: 60000
    # druid 监控平台相关配置
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
      stat-view-servlet:
        enable: true
        url-pattern: /druid/*
        login-username: admin
        login-password: tiger


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liuapi.incubator.repository.model
logging:
  level:
    root: info
    com.liuapi.incubator.repository: debug
server:
  port: 80