spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usercenter?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tiger
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com.liuapi.incubator.repository: debug